insert into Alien VALUES(101,'Rahul',true,'picture/sun1.jpg','java');
insert into Alien VALUES(102,'Anuj',false,'picture/sun2.jpg','.net');
insert into Alien VALUES(103,'Sunny',false,'picture/sun3.jpg','AI');
insert into Alien VALUES(104,'Atul',false,'picture/sun12.jfif','ML');
insert into Alien VALUES(105,'Pravin',false,'picture/sun5.jpg','MVC');
insert into Alien VALUES(106,'Sonu',true,'picture/sun6.jpg','Infra');
insert into Alien VALUES(107,'Tom',false,'picture/sun7.jpg','Angular');
insert into Alien VALUES(108,'John',false,'picture/sun8.jpeg','CSS');
insert into Alien VALUES(109,'Tim',false,'picture/sun9.jpg','Biz Dev');
insert into Alien VALUES(110,'Suchi',false,'picture/sun10.jpg','Tech');
insert into Alien VALUES(111,'Shaw',false,'picture/sun14.jfif','React');
insert into Alien VALUES(112,'Saurabh',false,'picture/sun12.jfif','Per. Test');
insert into Alien VALUES(113,'Himanshu',false,'picture/sun13.jfif','RPA');
insert into Alien VALUES(114,'Vishal',false,'picture/sun14.jfif','Hadoop');
insert into Alien VALUES(115,'Pulkit',false,'picture/sun15.jfif','SaaS');
insert into Alien VALUES(116,'Prashant',false,'picture/sun16.jpg','Andriod');
insert into Alien VALUES(117,'Sahu',false,'picture/sun14.jfif','Django');
insert into Alien VALUES(118,'Naved',false,'picture/sun1.jpg','Tech1');
insert into Alien VALUES(119,'Javed',false,'picture/sun2.jpg','Tech2');
insert into Alien VALUES(120,'Aslam',false,'picture/sun3.jpg','Tech3');
insert into Alien VALUES(121,'Salman',false,'picture/sun12.jfif','Tech4');
insert into Alien VALUES(122,'Yakub',false,'picture/sun5.jpg','Tech5');
insert into Alien VALUES(123,'Udal',false,'picture/sun6.jpg','Tech6');
insert into Alien VALUES(124,'Vinod',false,'picture/sun7.jpg','Tech7');
insert into Alien VALUES(125,'Sunil',false,'picture/sun8.jpeg','Tech8');
insert into Alien VALUES(126,'Kullu',false,'picture/sun9.jpg','Tech9');
insert into Alien VALUES(127,'Annie',false,'picture/sun10.jpg','Tech11');
insert into Alien VALUES(128,'Maria',false,'picture/sun14.jfif','Tech22');
insert into Alien VALUES(129,'Pinto',false,'picture/sun12.jfif','Tech33');
insert into Alien VALUES(130,'James',false,'picture/sun13.jfif','Tech44');
insert into Alien VALUES(131,'Nelson',false,'picture/sun14.jfif','Tech55');
insert into Alien VALUES(132,'Danial',false,'picture/sun15.jfif','Tech66');
insert into Alien VALUES(133,'Peter',false,'picture/sun16.jpg','Tech77');
insert into Alien VALUES(134,'David',false,'picture/sun14.jfif','Timer');
insert into Alien VALUES(135,'Lothar',false,'picture/sun1.jpg','Wso2');
insert into Alien VALUES(136,'Umesh',false,'picture/sun2.jpg','Python');
insert into Alien VALUES(137,'Pravita',false,'picture/sun3.jpg','Ruby');
insert into Alien VALUES(138,'Sultan',false,'picture/sun12.jfif','Scala');
insert into Alien VALUES(139,'Preeti',false,'picture/sun5.jpg','Devops');

 